---
# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

tasks:
  default:
    deps:
      - task: build
      - task: assets

  watch:
    deps:
      - task: run:watch
      - task: assets:watch

  run:watch:
    cmds:
      - air

  build:
    cmds:
      - go build -v main.go


  assets:watch:
    cmds:
      - npx @tailwindcss/cli -i ./static/style.css -o ./static/output.css --watch
    sources:
      - ./static/style.css
      - ./static/*.html
      - ./tailwind.config.js
    generates:
      - static/output.css

  assets:
    cmds:
      - npx @tailwindcss/cli -i ./static/style.css -o ./static/output.css
    sources:
      - ./static/style.css
      - ./static/*.html
      - ./tailwind.config.js
    generates:
      - static/output.css
